# Generated by Django 5.1 on 2024-08-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sujauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='campus',
            field=models.CharField(choices=[('ara', 'Aracati'), ('for', 'Fortaleza'), ('ndf', 'Não definido')], default='ndf', max_length=3),
        ),
    ]
