# Generated by Django 5.1 on 2024-08-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sujauth', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='campus',
            field=models.CharField(choices=[('ndf', 'Não definido'), ('ara', 'Aracati'), ('for', 'Fortaleza')], default='ndf', max_length=3),
        ),
    ]
